version: '3.2'
services:
    portainer:
        image: portainer/portainer
        networks:
            - main-network
        ports:
            - '8000:8000'
            - '9000:9000'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer-data:/data
        restart: always

    nginx-reverse-proxy:
        build: ./base_server
        image: nginx-base:latest
        networks:
            - main-network
            - applications-network
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - nginx-reverse-html:/usr/share/nginx/html
            - nginx-reverse-config:/etc/nginx
            - nginx-reverse-certs:/etc/letsencrypt
        restart: always

networks:
    main-network:
        driver: overlay
        attachable: true
    applications-network:
        driver: overlay
        attachable: true

volumes:
    portainer-data:
    nginx-reverse-html:
    nginx-reverse-config:
    nginx-reverse-certs:
