version: '3.2'
services:
    portainer:
        image: portainer/portainer
        container_name: portainer
        networks:
            - main_network
        ports:
            - '8000:8000'
            - '9000:9000'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        restart: always

    nginx_reverse_proxy:
        build: ./base_server
        image: nginx-base:latest
        container_name: nginx_reverse_proxy
        networks:
            - main_network
            - applications_network
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - nginx_reverse_html:/usr/share/nginx/html
            - nginx_reverse_config:/etc/nginx
            - nginx_reverse_certs:/etc/letsencrypt
        restart: always

networks:
    main_network:
        driver: overlay
        attachable: true
    applications_network:
        driver: overlay
        attachable: true

volumes:
    portainer_data:
    nginx_reverse_html:
    nginx_reverse_config:
    nginx_reverse_certs:
